travis:
  secure:
    BINSTAR_TOKEN: BckE7Bg5VfZNUZPSRjitSkMVpHnbvzVQ/5vQ5nProgKJCbly13bmNSOYE+LVT8iGBtoR6mCQLQLE1ec5xFZa7Eq10tMd5BHMe8cFN4oLbP+RH3R3Hcl7ESD8+kjqNRELzSRo1CPH/Hg6KnKtZW40p/CBWGZM5f2NJauiY8ivaB1BebMdvT9DLMUZ4jz7i4ZkBKKEiczn94lKXIbP8X6tJNQ8YDyXQK5fra+18ZMq9D5cCJXSbptV2+IWstArMi1s+AsT3pe5WHaxDxzumvb91HnHCdvxWaKbQVv0FiWkkRZptWFpvUd7PhSh2Slk22RMjo/zrVZfhGCcPKmJQIbFtXy8YcxB25qY4Azkxj5/jH81aajuS+7xCb4Njjymh6sb+1OnmmlOHq2BrCO7WPZaCh8rl0FImu4is/RK4rKwpz1Hwl6MtNEwl3QZeKIxFWZedCMPqfCq6gW8mj8JkK9qtn1Pf/UWJsKQdgm20g5ryt18KuGPpDh2cwdAgyT/HdE4AIQyM2f6fru1d19leh4z9bZaQuN0mX8AljwqqDpgKgBvtAS43OqiTimYfp/GsUIEkZa2X1Xkgwfkqfa9iBfTHfz9ZvzdKBRhytRH3U7knj21HfOQxbFT9+cKn6Zya5yFMpYr08O4TCdcLCPs5xcB5f40dnAX2OAMTre1hgQ+E9w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
