travis:
  secure:
    BINSTAR_TOKEN: Dx/xWQF+83HL1I20YldPO3h8fSEBch8Grqp5kgnxGst6ZfL+D9qc/8HiBJW7CRWy9fSQk47UKN8UVRSB8HnP92YfyeHM0cNT14lEgg6bJm1dYq0c4VO7Kw1vEV4WkBZ/7hG1sX1E1MUUjPAYz6DD1bOh66Jwzl3B5ONfFWsiSbtuyiTkeBaNF3ia8y0AzbE3hBXlzK2sy1nPXoEcCvdKphYdh4dUpHN0WrQoWQON85j2/BkpdrO9c1E6e6PqlmUWPCWSsGOSOQZ0F/Yansd0a7X7FdpMk1rU1XB5a9BVjUnFYECRNSYCEKPmE/0whu7/Aku9cPMTjYJrbjMKt62rrL3LX2Pq3hWq/ra+KLgb0bNTImmtsfPaVehLXn606eHQbPJej/Zxmay04RYL6gko10FKvpUNhciO2vTl7OhFJqeWSf31s/HMoVuP4wBQEWGWgdICh49aGdbpP4qyxamTglWAyhMg99HaG1cillt6CL4zO6us/ni4JtgnJD9lHzNb5UR0aqudQHqVf4wAORfZV444CtCIe6kAbsK041bmcOzNZ7YwVk9v9YRqJp55IUbPeXoCEVbmo5xWqCJsD9+/joIOZUG2ZY0SJACGev7TY05k7um4F3fziCLXyAmtFPIUeEC9UOCavMByBsWcIjD01vamamXZhi8e4Pzc44oo7yk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
